# TODO: is there any way to dynamically reference this file?
name: "Publish Docker Images"
description: "Common logic for publishing docker images from this repository"

inputs:
  username:
    description: "The username for publishing to the docker registry"
    required: true
  password:
    description: "The password for publishing to the docker registry"
    required: true
  tag:
    description: "The tag of the docker image to publish"
    required: true
  platforms:
    description: "The targetted platforms for this image"
    required: true

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v6
  - uses: docker/setup-qemu-action@v3
  - uses: docker/setup-buildx-action@v3
  - uses: docker/login-action@v3
    with:
      username: "${{ inputs.username }}"
      password: "${{ inputs.password }}"
  - uses: actions/github-script@v8
    id: tag
    with:
      result-encoding: string
      script: "return '${{ inputs.tag }}'.replace('/', '').replace('-', '')"
  - uses: docker/build-push-action@v6
    with:
      context: "./${{ inputs.tag }}/.."
      file: "./${{ inputs.tag }}/Dockerfile"
      platforms: "${{ inputs.platforms }}"
      push: true
      tags: |
        ${{ inputs.username }}/yolks:${{ steps.tag.outputs.result }}
