name: "Publish Docker Images"

inputs:
  username:
    required: true
  password:
    required: true
  tag:
    required: true
  platforms:
    required: true

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
  - uses: docker/setup-qemu-action@v3
  - uses: docker/setup-buildx-action@v3
  - uses: docker/login-action@v3
    with:
      username: "${{ inputs.username }}"
      password: "${{ inputs.password }}"
  - uses: actions/github-script@v7
    id: tag
    with:
      result-encoding: string
      script: "return '${{ inputs.tag }}'.replace('/', '').replace('-', '')"
  - uses: docker/build-push-action@v4
    with:
      context: "./${{ inputs.tag }}/.."
      file: "./${{ inputs.tag }}/Dockerfile"
      platforms: "${{ inputs.platforms }}"
      push: true
      tags: |
        ${{ inputs.username }}/yolks:${{ steps.tag.outputs.result }}
