name: Publish Images
on:
  workflow_dispatch:
jobs:
  push:
    name: "Build ${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          # todo add tags back
          - nodejs/20
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}
      - uses: actions/github-script@v7
        id: tagger
        with:
          result-encoding: string
          script: "return '${{ matrix.tag }}'.replace('/', '').replace('-', '')"
      - uses: docker/build-push-action@v4
        with:
          context: "./${{ matrix.tag }}/.."
          file: "./${{ matrix.tag }}/Dockerfile"
          platforms: "linux/amd64,linux/arm64"
          push: true
          tags: |
            ${{ secrets.REGISTRY_USER }}/yolks:${{ steps.tagger.outputs.result }}