name: Publish MariaDB Images
on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - mariadb/**
jobs:
  push:
    name: "Build ${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
        - mariadb/10.5
        - mariadb/10.6
        - mariadb/10.11
        - mariadb/11.2
        - mariadb/11.4
        - mariadb/11.5
    steps:
    - uses: "booky10/yolks/.github/actions/publish-docker@master"
      with:
        username: "${{ secrets.REGISTRY_USER }}"
        password: "${{ secrets.REGISTRY_PASS }}"
        tag: "${{ matrix.tag }}"
        platforms: "linux/amd64,linux/arm64"
