name: Publish Python Images
on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - python/**
jobs:
  push:
    name: "Build ${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
        - python/3.9
        - python/3.10
        - python/3.11
        - python/3.12
        - python/3.13
    steps:
    - uses: "booky10/yolks/.github/actions/publish-docker@master"
      with:
        username: "${{ secrets.REGISTRY_USER }}"
        password: "${{ secrets.REGISTRY_PASS }}"
        tag: "${{ matrix.tag }}"
        platforms: "linux/amd64,linux/arm64"
