name: Publish NodeJS Gyp Images
on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - nodejs-gyp/**
jobs:
  push:
    name: "Build ${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
        - nodejs-gyp/20
        - nodejs-gyp/22
        - nodejs-gyp/24
    steps:
    - uses: "booky10/yolks/.github/actions/publish-docker@master"
      with:
        username: "${{ secrets.REGISTRY_USER }}"
        password: "${{ secrets.REGISTRY_PASS }}"
        tag: "${{ matrix.tag }}"
        platforms: "linux/amd64,linux/arm64"
