name: Publish Java Images
on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - java/**
jobs:
  push:
    name: "Build ${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
        - java/8
        - java/11
        - java/17
        - java/21
        - java/25
    steps:
    - uses: "booky10/yolks/.github/actions/publish-docker@master"
      with:
        username: "${{ secrets.REGISTRY_USER }}"
        password: "${{ secrets.REGISTRY_PASS }}"
        tag: "${{ matrix.tag }}"
        platforms: "linux/amd64,linux/arm64"
