name: Publish Go NodeJS Images
on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - go-nodejs/**
jobs:
  push:
    name: "Build ${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
        - go-nodejs/1.23-20
        - go-nodejs/1.23-22
        - go-nodejs/1.23-23
        - go-nodejs/1.23-24
        - go-nodejs/1.24-20
        - go-nodejs/1.24-22
        - go-nodejs/1.24-23
        - go-nodejs/1.24-24
    steps:
    - uses: "booky10/yolks/.github/actions/publish-docker@master"
      with:
        username: "${{ secrets.REGISTRY_USER }}"
        password: "${{ secrets.REGISTRY_PASS }}"
        tag: "${{ matrix.tag }}"
        platforms: "linux/amd64,linux/arm64"
